name: Run 2 Tsan clang14 aslr 28
on:
  push:
jobs:
  run-tsan:
    name: '${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2 

      - name: Install dependencies for project (Linux)
        if: runner.os == 'Linux'
        run: | 
          sudo apt-get update
          sudo apt-get install -y autotools-dev automake libevent-dev  
      - name: Install ThreadSanitizer dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get install -y clang-14 libclang-14-dev llvm-14 llvm-14-dev llvm-14-tools llvm-14-linker-tools
      - name: Build repository 
        run: | 
          clang++ -fsanitize=address,fuzzer -fPIE -fPIC -O2 -g -gcolumn-info fuzz_me.cc

      
      - name: Run Google Thread Sanitizer (executables) (Linux)
        if: runner.os == 'Linux'
        run: |
            #!/bin/bash
            set +e
            ./a.out 2>&1 | grep ERROR
